### ISSUE TITLE
[Question] Installation

### ISSUE THREAD

**Issue by PascalSoftwares** [DevHrytsan/FlaxObjectPool#1]
Your installation process says
> Navigate to Tools -> Plugins -> Clone Plugin Project.
> Enter the following URL: https://github.com/DevHrytsan/FlaxObjectPool.git.
But there is no plugin to clone in empty new project - how to manually add one?

**Comment by DevHrytsan** [comment]
Oh. I am sorry, forgot to mention it in Readme. It's for Flax Engine master or 1.7 branch method. Developers in this version have added the ability to easily install and clone plugins.
If you use Flax Engine 1.6, You need to do it manually.  Check the readme file again.
